#!/usr/bin/env bash

# Copyright (c) 2018-2019, NuoDB, Inc.
# All rights reserved.
#
# Redistribution and use permitted under the terms of the 3-clause BSD license.

docker stop te1 sm1 ad1
docker network rm nuodb-net
rm -fr vol1 vol2
