#!/usr/bin/env bash

# Copyright (c) 2018-2019, NuoDB, Inc.
# All rights reserved.
#
# Redistribution and use permitted under the terms of the 3-clause BSD license.

: ${IMG_NAME:="nuodb/nuodb-ce:latest"}

docker run -it --net nuodb-net ${IMG_NAME} \
    nuocmd --api-server ad1:8888 show domain

